update autodeploy

diff --git a/bin/automated b/bin/automated
--- a/bin/automated
+++ b/bin/automated
@@ -1,3 +1,39 @@
 #!/bin/bash
 
-echo "hi"
+# Automated deploy script with Circle CI.
+
+# Exit if any subcommand fails.
+set -e
+
+# Variables
+ORIGIN_URL=https://github.com/afiedler/andyfiedler-com
+
+echo "Started deploying"
+
+# Checkout gh-pages branch.
+if [ `git branch | grep gh-pages` ]
+then
+  git branch -D gh-pages
+fi
+git checkout -b gh-pages
+
+
+# Delete and move files.
+find . -maxdepth 1 ! -name '_site' ! -name '.git' ! -name '.gitignore' -exec rm -rf {} \;
+mv _site/* .
+rm -R _site/
+
+# Push to gh-pages.
+git config user.name "CircleCI Auto-deploy"
+git config user.email "andy@andyfiedler.com"
+
+git add -fA
+git commit --allow-empty -m "$(git log -1 --pretty=%B) [ci skip]"
+git push -f $ORIGIN_URL gh-pages
+
+# Move back to previous branch.
+git checkout -
+
+echo "Deployed Successfully!"
+
+exit 0
